version: '3'
services:
  softplan-desafio-fullstack-marcelo-anzolin:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: softplan-desafio-fullstack-marcelo-anzolin/api
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - PROFILE=dev
    links:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_DB=gprocessosoftplan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./docker/volume_postgres:/var/lib/postgres